[build]
  publish = "build/"
  command = "npm run build"

[build.environment]
  CI = "true"

[[plugins]]
  package = "/plugins/netlify-plugin-prettier"

[[plugins]]
  package = "/plugins/netlify-plugin-firebase-cache"

[[plugins]]
  package = "/plugins/netlify-plugin-unit-test"
